CREATE TABLE Pilotos(
PIL_ID INT AUTO_INCREMENT PRIMARY KEY,
PIL_NOME VARCHAR(30),
PIL_SOBRENOME VARCHAR(30),
EQI_EQUIPE INT,
PIL_PODIOS INT,
PIL_PONTOS_TOTAIS INT,
PIL_CORRIDAS_OFICIAIS INT,
PIL_CAMPEAO VARCHAR(10),
PIL_MELHOR_CHEGADA VARCHAR(10),
STA_ATIVO INT,
PIL_ULTIMA_TEMPORADA INT,
PIL_VOLTAS_RAPIDAS INT
)